(function(){
  'use strict';
  var STAGES={GENERAL:'GENERAL',TOP_16:'TOP_16',TOP_8:'TOP_8',TOP_4:'TOP_4',SEMIFINAL:'SEMIFINAL',FINAL:'FINAL',FINISHED:'FINISHED'},LABELS={GENERAL:'Clasificación general',TOP_16:'Top 16',TOP_8:'Top 8',TOP_4:'Top 4',SEMIFINAL:'Semifinales',FINAL:'Final',FINISHED:'Finalizado'},STATUS={ACTIVE:'ACTIVE',QUALIFIED:'QUALIFIED',ELIMINATED:'ELIMINATED',CHAMPION:'CHAMPION',RUNNER_UP:'RUNNER_UP'},STATUS_LABELS={ACTIVE:'Activo',QUALIFIED:'Clasificado',ELIMINATED:'Eliminado',CHAMPION:'Campeón',RUNNER_UP:'Subcampeón'},KEY='puntaje-newcom-state';
  var app=document.getElementById('app'),modal=document.getElementById('modal'),state,view='home',theme='light';
  function empty(){return{categories:[],teams:[],results:[],selectedCategoryId:null,theme:'light'};}
  function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c];});}
  function initial(v){return(String(v||'').trim().charAt(0)||'?').toUpperCase();}
  function isStage(v){return Object.keys(STAGES).some(function(k){return STAGES[k]===v;});}
  function isStatus(v){return Object.keys(STATUS).some(function(k){return STATUS[k]===v;});}
  function sum(values){return values.reduce(function(total,value){return total+value;},0);}

  /* Migración segura: no reasigna equipos huérfanos; solo convierte sets legacy a points. */
  function normalize(raw){
    if(!raw||typeof raw!=='object')return empty();
    var categories=Array.isArray(raw.categories)?raw.categories:[],categoryIds={};
    categories=categories.filter(function(c){if(!c||typeof c.id!=='string'||!c.id||typeof c.name!=='string'||!c.name.trim()||categoryIds[c.id])return false;categoryIds[c.id]=true;return true;}).map(function(c){return{id:c.id,name:c.name.trim(),currentStage:isStage(c.currentStage)?c.currentStage:STAGES.GENERAL,championId:typeof c.championId==='string'?c.championId:null,runnerUpId:typeof c.runnerUpId==='string'?c.runnerUpId:null};});
    var sourceTeams=Array.isArray(raw.teams)?raw.teams:[],teamIds={},teams=sourceTeams.filter(function(t){if(!t||typeof t.id!=='string'||!t.id||teamIds[t.id]||typeof t.name!=='string'||!t.name.trim()||typeof t.categoryId!=='string'||!categoryIds[t.categoryId])return false;teamIds[t.id]=true;return true;}).map(function(t){return{id:t.id,name:t.name.trim(),categoryId:t.categoryId,status:isStatus(t.status)?t.status:STATUS.ACTIVE,stage:isStage(t.stage)?t.stage:(isStage(t.currentStage)?t.currentStage:STAGES.GENERAL),results:[],totalPoints:0};});
    var sourceResults=Array.isArray(raw.results)?raw.results:[],resultIds={},results=sourceResults.filter(function(r){return r&&typeof r.id==='string'&&r.id&&typeof r.teamId==='string'&&teamIds[r.teamId];}).map(function(r){var value=null;if(Number.isInteger(r.points)&&r.points>=0)value=r.points;else if(Array.isArray(r.setScores)&&r.setScores.every(function(n){return Number.isInteger(n)&&n>=0;}))value=sum(r.setScores);else if(Number.isInteger(r.totalPoints)&&r.totalPoints>=0)value=r.totalPoints;if(value===null)return null;var team=teams.filter(function(t){return t.id===r.teamId;})[0];return{id:r.id,teamId:r.teamId,points:value,createdAt:typeof r.createdAt==='string'?r.createdAt:new Date().toISOString(),stage:isStage(r.stage)?r.stage:team.stage};}).filter(Boolean).filter(function(r){if(resultIds[r.id])return false;resultIds[r.id]=true;return true;});
    teams.forEach(function(t){var own=results.filter(function(r){return r.teamId===t.id;});t.results=own.map(function(r){return r.id;});t.totalPoints=sum(own.map(function(r){return r.points;}));});
    var selected=typeof raw.selectedCategoryId==='string'&&categoryIds[raw.selectedCategoryId]?raw.selectedCategoryId:(categories[0]?categories[0].id:null);
    return{categories:categories,teams:teams,results:results,selectedCategoryId:selected,theme:raw.theme==='dark'?'dark':'light'};
  }
  function loadState(){try{var raw=localStorage.getItem(KEY);if(!raw)return empty();var parsed=JSON.parse(raw),normalized=normalize(parsed);if(JSON.stringify(parsed)!==JSON.stringify(normalized))localStorage.setItem(KEY,JSON.stringify(normalized));return normalized;}catch(e){console.warn('No se pudo leer localStorage; se inició vacío.',e);return empty();}}
  function syncTeams(){state.teams.forEach(function(t){var own=state.results.filter(function(r){return r.teamId===t.id;});t.results=own.map(function(r){return r.id;});t.totalPoints=sum(own.map(function(r){return r.points;}));});}
  function saveState(){try{syncTeams();localStorage.setItem(KEY,JSON.stringify(state));}catch(e){console.warn('No se pudo guardar localStorage.',e);}}
  function category(){return state.categories.filter(function(c){return c.id===state.selectedCategoryId;})[0]||null;}
  function teams(categoryId){return state.teams.filter(function(t){return t.categoryId===categoryId;});}
  function teamById(id){return state.teams.filter(function(t){return t.id===id;})[0]||null;}
  function active(categoryId){return teams(categoryId).filter(function(t){return t.status===STATUS.ACTIVE||t.status===STATUS.QUALIFIED;});}
  function results(categoryId){var ids=teams(categoryId).map(function(t){return t.id;});return state.results.filter(function(r){return ids.indexOf(r.teamId)>=0;});}
  function standings(categoryId,stage){return teams(categoryId).map(function(team){var all=state.results.filter(function(r){return r.teamId===team.id;}),current=all.filter(function(r){return r.stage===stage;});return{team:team,results:current,resultCount:current.length,stagePoints:sum(current.map(function(r){return r.points;})),totalPoints:sum(all.map(function(r){return r.points;}))};}).sort(function(a,b){return b.stagePoints-a.stagePoints||b.totalPoints-a.totalPoints||a.team.name.localeCompare(b.team.name);});}
  function visibleRows(){var c=category();if(!c)return[];return standings(c.id,c.currentStage).filter(function(row){return c.currentStage===STAGES.GENERAL||row.team.status===STATUS.ACTIVE||row.team.status===STATUS.QUALIFIED||(c.currentStage===STAGES.FINISHED&&(row.team.status===STATUS.CHAMPION||row.team.status===STATUS.RUNNER_UP));}).sort(function(a,b){return b.totalPoints-a.totalPoints||b.stagePoints-a.stagePoints||a.team.name.localeCompare(b.team.name);});}

  function selectCategory(id,nextView){if(!state.categories.some(function(c){return c.id===id;}))throw Error('Categoría inexistente.');state.selectedCategoryId=id;saveState();if(nextView)view=nextView;render();}
  function createCategory(name){name=String(name||'').trim();if(!name)throw Error('La categoría necesita un nombre.');var c={id:uid('cat'),name:name,currentStage:STAGES.GENERAL,championId:null,runnerUpId:null};state.categories.push(c);state.selectedCategoryId=c.id;saveState();return c;}
  function editCategory(id,name){var c=state.categories.filter(function(x){return x.id===id;})[0];name=String(name||'').trim();if(!c)throw Error('Categoría inexistente.');if(!name)throw Error('La categoría necesita un nombre.');c.name=name;saveState();}
  function deleteCategory(id){if(!state.categories.some(function(c){return c.id===id;}))throw Error('Categoría inexistente.');var ids=teams(id).map(function(t){return t.id;});state.categories=state.categories.filter(function(c){return c.id!==id;});state.teams=state.teams.filter(function(t){return ids.indexOf(t.id)<0;});state.results=state.results.filter(function(r){return ids.indexOf(r.teamId)<0&&state.teams.some(function(t){return t.id===r.teamId;});});state.selectedCategoryId=state.categories[0]?state.categories[0].id:null;saveState();}
  function createTeam(name){var c=category();name=String(name||'').trim();if(!c)throw Error('Seleccioná una categoría.');if(c.currentStage!==STAGES.GENERAL)throw Error('No se pueden agregar equipos después de iniciar el torneo.');if(!name)throw Error('El equipo necesita un nombre.');state.teams.push({id:uid('team'),name:name,categoryId:c.id,status:STATUS.ACTIVE,stage:STAGES.GENERAL,results:[],totalPoints:0});saveState();}
  function addResult(teamId,value){var c=category(),team=teamById(teamId),points=Number(value);if(!c||!team||team.categoryId!==c.id)throw Error('Equipo inválido para esta categoría.');if([STATUS.ELIMINATED,STATUS.CHAMPION,STATUS.RUNNER_UP].indexOf(team.status)>=0)throw Error('Este equipo no puede recibir resultados.');if(c.currentStage===STAGES.FINISHED)throw Error('El torneo ya finalizó.');if(!Number.isInteger(points)||points<0)throw Error('El puntaje debe ser un número entero mayor o igual a 0.');state.results.push({id:uid('result'),teamId:team.id,points:points,createdAt:new Date().toISOString(),stage:c.currentStage});saveState();}
  function addQuickResults(entries){var c=category();if(!c)throw Error('Seleccioná una categoría.');if(c.currentStage===STAGES.FINISHED)throw Error('El torneo ya finalizó.');var pending=[];entries.forEach(function(entry){if(entry.value===''||entry.value===null||typeof entry.value==='undefined')return;var team=teamById(entry.teamId),points=Number(entry.value);if(!team||team.categoryId!==c.id)throw Error('Hay un equipo que no pertenece a la categoría activa.');if([STATUS.ELIMINATED,STATUS.CHAMPION,STATUS.RUNNER_UP].indexOf(team.status)>=0)throw Error('Hay un equipo que no puede recibir resultados.');if(!Number.isInteger(points)||points<0)throw Error('Cada puntaje debe ser un número entero mayor o igual a 0.');pending.push({id:uid('result'),teamId:team.id,points:points,createdAt:new Date().toISOString(),stage:c.currentStage});});if(!pending.length)throw Error('Ingresá al menos un puntaje para guardar.');state.results=state.results.concat(pending);saveState();return pending.length;}
  function deleteResult(id){state.results=state.results.filter(function(r){return r.id!==id;});saveState();}
  function advance(target,limit){var c=category();if(!c)throw Error('Seleccioná una categoría.');var list=active(c.id);if(list.length<2)throw Error('Se necesitan al menos 2 equipos activos.');var ranking=standings(c.id,c.currentStage).filter(function(row){return list.some(function(t){return t.id===row.team.id;});}),keep=ranking.slice(0,Math.min(limit,list.length)).map(function(row){return row.team.id;});list.forEach(function(t){if(keep.indexOf(t.id)>=0){t.status=STATUS.QUALIFIED;t.stage=target;}else t.status=STATUS.ELIMINATED;});c.currentStage=target;saveState();}
  function generateTop16(){var c=category();if(!c||c.currentStage!==STAGES.GENERAL)throw Error('La etapa actual no es clasificación general.');advance(STAGES.TOP_16,16);}
  function generateTop8(){var c=category();if(!c||c.currentStage!==STAGES.TOP_16)throw Error('La etapa actual no es Top 16.');advance(STAGES.TOP_8,8);}
  function generateTop4(){var c=category();if(!c||c.currentStage!==STAGES.TOP_8)throw Error('La etapa actual no es Top 8.');advance(STAGES.TOP_4,4);}
  function advanceToSemifinals(){var c=category();if(!c||c.currentStage!==STAGES.TOP_4)throw Error('La etapa actual no es Top 4.');advance(STAGES.SEMIFINAL,4);}
  function advanceToFinal(){var c=category();if(!c||c.currentStage!==STAGES.SEMIFINAL)throw Error('La etapa actual no es semifinales.');advance(STAGES.FINAL,2);}
  function finishTournament(){var c=category();if(!c||c.currentStage!==STAGES.FINAL)throw Error('La categoría no está en la final.');var rows=standings(c.id,STAGES.FINAL).filter(function(r){return r.team.status===STATUS.ACTIVE||r.team.status===STATUS.QUALIFIED;});if(rows.length<2||!rows[0].resultCount||!rows[1].resultCount)throw Error('Cargá un resultado para cada finalista.');c.championId=rows[0].team.id;c.runnerUpId=rows[1].team.id;c.currentStage=STAGES.FINISHED;rows[0].team.status=STATUS.CHAMPION;rows[1].team.status=STATUS.RUNNER_UP;saveState();}

  function badge(status){return'<span class="status '+status+'">'+STATUS_LABELS[status]+'</span>';}
  function stats(){var c=category(),scope=c?results(c.id):[];return'<div class="summary"><div class="stat"><i>▦</i><div><small>CATEGORÍAS</small><b>'+state.categories.length+'</b></div></div><div class="stat"><i>♙</i><div><small>EQUIPOS</small><b>'+state.teams.length+'</b></div></div><div class="stat"><i>●</i><div><small>RESULTADOS</small><b>'+state.results.length+'</b></div></div><div class="stat"><i>★</i><div><small>PUNTOS '+(c?'ACTIVOS':'')+'</small><b>'+sum(scope.map(function(r){return r.points;}))+'</b></div></div><div class="stat"><i>◈</i><div><small>ETAPA ACTUAL</small><b>'+(c?LABELS[c.currentStage]:'Clasificación')+'</b></div></div></div>';}
  function sidebar(){var c=category();return'<aside class="sidebar"><div class="brand"><span class="logo">P</span><div><b>Puntaje</b><small>NEWCOM</small></div></div><nav class="nav"><div class="nav-label">NAVEGACIÓN</div><button data-view="home" class="'+(view==='home'?'active':'')+'"><span>⌂</span> Inicio</button><button data-view="categories" class="'+(view==='categories'?'active':'')+'"><span>▦</span> Categorías <em>'+state.categories.length+'</em></button>'+(c?'<div class="nav-label" style="margin-top:22px">CATEGORÍA ACTIVA</div><button data-view="teams" class="'+(view==='teams'?'active':'')+'"><span>♙</span> Equipos</button><button data-view="results" class="'+(view==='results'?'active':'')+'"><span>＋</span> Resultados</button><button data-view="table" class="'+(view==='table'?'active':'')+'"><span>▤</span> Tabla general</button><button data-view="stage" class="'+(view==='stage'?'active':'')+'"><span>◈</span> Etapa actual</button>':'')+'</nav><div class="sidebar-foot"><div class="tip">● &nbsp;<strong>Solo puntajes y clasificación.</strong></div><small>v1.0 · Puntaje Newcom</small></div></aside>';}
  function shell(content){var c=category();return'<div class="app">'+sidebar()+'<div class="main"><header class="topbar"><div class="mobile-brand"><span class="logo">P</span><b>Puntaje Newcom</b></div><div class="crumb"><small>PUNTAJE NEWCOM</small><b>'+(c?esc(c.name):'Resumen general')+'</b></div><button class="theme" data-action="theme">'+(theme==='dark'?'☀ Modo claro':'☾ Modo oscuro')+'</button></header><main>'+content+'</main></div></div>';}
  function categoryPicker(){return'<label class="category-picker">Categoría<select data-action="select-category">'+state.categories.map(function(c){return'<option value="'+c.id+'" '+(c.id===state.selectedCategoryId?'selected':'')+'>'+esc(c.name)+'</option>';}).join('')+'</select></label>';}
  function categoriesPage(){return'<div class="heading"><div><p class="eyebrow">ADMINISTRACIÓN</p><h1>Categorías</h1><p class="desc">Cada categoría tiene sus equipos, resultados y etapas.</p></div><button class="primary" data-action="new-category">＋ Nueva categoría</button></div><div id="notice"></div><div class="category-grid">'+(state.categories.length?state.categories.map(function(c){return'<article class="category-card"><button class="category-card-open" data-category="'+c.id+'"><span class="avatar">'+initial(c.name)+'</span><h3>'+esc(c.name)+'</h3><span class="badge">'+LABELS[c.currentStage]+'</span><div class="meta"><span>'+teams(c.id).length+' equipos</span><span>'+results(c.id).length+' resultados</span></div></button><div class="actions"><button class="link" data-action="edit-category" data-id="'+c.id+'">Editar</button><button class="link danger" data-action="delete-category" data-id="'+c.id+'">🗑 Eliminar</button></div></article>';}).join(''):'<section class="card empty"><h2>No hay categorías creadas.</h2><p>Creá la primera categoría para comenzar.</p><button class="primary" data-action="new-category">＋ Crear categoría</button></section>')+'</div>';}
  function home(){return'<div class="heading"><div><p class="eyebrow">PANEL PRINCIPAL</p><h1>Puntaje Newcom</h1><p class="desc">Gestión de resultados y clasificación de torneos.</p></div><button class="primary" data-action="new-category">＋ Crear categoría</button></div>'+stats()+'<div id="notice"></div>'+(state.categories.length?'<section class="card"><div class="card-title"><div><p class="eyebrow">CATEGORÍAS</p><h2>Tus torneos</h2></div><button class="link" data-view="categories">Ver todas →</button></div>'+state.categories.map(function(c){return'<button class="category-row" data-category="'+c.id+'"><span class="avatar">'+initial(c.name)+'</span><span class="category-name"><b>'+esc(c.name)+'</b><small>'+teams(c.id).length+' equipos</small></span><span class="badge">'+LABELS[c.currentStage]+'</span><span>→</span></button>';}).join('')+'</section>':'<section class="card empty"><div class="big">◎</div><h2>No hay categorías creadas.</h2><p>Creá una categoría para cargar equipos y resultados.</p><button class="primary" data-action="new-category">＋ Crear categoría</button></section>');}
  function categoryHeader(c){return'<div class="heading"><div><p class="eyebrow">CATEGORÍA</p><h1>'+esc(c.name)+'</h1><p class="desc">'+active(c.id).length+' activos · '+teams(c.id).length+' equipos · <span class="stage-text">'+LABELS[c.currentStage]+'</span></p></div><div class="heading-actions"><span class="badge">'+LABELS[c.currentStage]+'</span><button class="link danger delete-category-button" data-action="delete-active-category" data-id="'+c.id+'">🗑 Eliminar categoría</button></div></div><div id="notice"></div><div class="tabs"><button data-view="teams" class="'+(view==='teams'?'active':'')+'">Equipos</button><button data-view="results" class="'+(view==='results'?'active':'')+'">Resultados</button><button data-view="table" class="'+(view==='table'?'active':'')+'">Tabla general</button><button data-view="stage" class="'+(view==='stage'?'active':'')+'">Etapa actual</button></div>';}
  function table(){var rows=visibleRows();return'<section class="card"><div class="card-title"><div><p class="eyebrow">TABLA GENERAL</p><h2>Clasificación</h2></div></div>'+(rows.length?'<div class="table-wrap"><table class="table"><thead><tr><th>POS.</th><th>EQUIPO</th><th>RESULTADOS</th><th>PUNTOS</th><th>ESTADO</th></tr></thead><tbody>'+rows.map(function(r,i){return'<tr><td><span class="pos '+(i<3?'top':'')+'">'+(i+1)+'</span></td><td><strong>'+esc(r.team.name)+'</strong></td><td>'+r.resultCount+'</td><td><strong>'+r.totalPoints+'</strong></td><td>'+badge(r.team.status)+'</td></tr>';}).join('')+'</tbody></table></div>':'<div class="empty"><p>No hay datos para mostrar.</p></div>')+'</section>';}
  function teamsPage(){var rows=visibleRows();return'<div class="toolbar"><div><h2>Equipos</h2><p class="desc">Equipos de '+esc(category().name)+'</p></div><button class="primary" data-action="new-team">＋ Agregar equipo</button></div><section class="card" style="margin-top:16px">'+(rows.length?'<div class="table-wrap"><table class="table"><thead><tr><th>POS.</th><th>EQUIPO</th><th>RESULTADOS</th><th>PUNTOS</th><th>ESTADO</th></tr></thead><tbody>'+rows.map(function(r,i){return'<tr><td><span class="pos '+(i<3?'top':'')+'">'+(i+1)+'</span></td><td><strong>'+esc(r.team.name)+'</strong></td><td>'+r.resultCount+'</td><td>'+r.totalPoints+'</td><td>'+badge(r.team.status)+'</td></tr>';}).join('')+'</tbody></table></div>':'<div class="empty"><p>No hay equipos todavía.</p></div>')+'<form class="inline" data-form="team"><input name="name" required placeholder="Nombre del equipo"><button class="secondary">Guardar equipo</button></form></section>';}
  function quickLoader(){var list=active(category().id);return'<form class="quick-loader" data-form="quick-results"><div class="quick-head"><div><p class="eyebrow">CARGA RÁPIDA</p><h2>Varios puntajes</h2></div><span class="desc">Solo se guardan los campos completos.</span></div><div class="quick-table"><div class="quick-row quick-labels"><span>Equipo</span><span>Puntaje</span></div>'+list.map(function(t){return'<label class="quick-row"><strong>'+esc(t.name)+'</strong><input name="quick-points" data-team-id="'+t.id+'" type="number" min="0" step="1" placeholder="—"></label>';}).join('')+'</div><button class="primary">Guardar puntajes</button></form>';}
  function resultForm(){var list=active(category().id);return'<form class="form result" data-form="result"><div class="form-grid"><div>'+categoryPicker()+'</div><label>Equipo<select name="teamId" required>'+list.map(function(t){return'<option value="'+t.id+'">'+esc(t.name)+'</option>';}).join('')+'</select></label></div><label>Puntaje<input name="points" type="number" min="0" step="1" required placeholder="Ej: 37"></label><button class="primary">Guardar puntaje</button></form>';}
  function resultsPage(){var c=category(),list=results(c.id).slice().reverse();return'<div class="two"><section class="card"><div class="card-title"><div><p class="eyebrow">CARGAR PUNTAJE</p><h2>Resultado individual</h2></div></div>'+(c.currentStage===STAGES.FINISHED?'<div class="empty"><p>El torneo finalizó.</p></div>':active(c.id).length?resultForm():'<div class="empty"><p>No hay equipos activos.</p></div>')+'</section><section class="card"><div class="card-title"><div><p class="eyebrow">HISTORIAL</p><h2>Resultados cargados</h2></div></div>'+(list.length?'<div>'+list.map(function(r){var t=teamById(r.teamId);return'<div class="recent-item"><span class="avatar">'+initial(t?t.name:'')+'</span><span><b>'+esc(t?t.name:'Equipo')+'</b><small>'+r.points+' puntos · '+LABELS[r.stage]+'</small></span><button class="link danger" data-action="delete-result" data-id="'+r.id+'">Eliminar</button></div>';}).join('')+'</div>':'<div class="empty"><p>No hay resultados.</p></div>')+'</section></div><section class="card quick-card"><div class="quick-category">'+categoryPicker()+'</div>'+(c.currentStage===STAGES.FINISHED?'<div class="empty"><p>El torneo finalizó.</p></div>':active(c.id).length?quickLoader():'<div class="empty"><p>No hay equipos para cargar.</p></div>')+'</section>';}
  function stagePage(){var c=category(),rows=visibleRows(),action=c.currentStage===STAGES.FINAL?'<button class="primary" data-action="finish">Determinar campeón</button>':c.currentStage===STAGES.FINISHED?'':'<button class="primary" data-action="advance">'+({GENERAL:'Generar Top 16',TOP_16:'Generar Top 8',TOP_8:'Generar Top 4',TOP_4:'Avanzar a semifinales',SEMIFINAL:'Avanzar a final'})[c.currentStage]+' →</button>',winner=c.championId&&teamById(c.championId),runner=c.runnerUpId&&teamById(c.runnerUpId),playoff=([STAGES.SEMIFINAL,STAGES.FINAL].indexOf(c.currentStage)>=0&&rows.length)?'<div class="playoff-board"><div class="card-title"><div><p class="eyebrow">'+(c.currentStage===STAGES.FINAL?'FINAL':'SEMIFINALES')+'</p><h2>'+(c.currentStage===STAGES.FINAL?'Equipo A vs Equipo B':'Equipos clasificados')+'</h2></div><button class="link" data-view="results">Cargar puntajes →</button></div><div class="playoff-grid">'+rows.map(function(r,i){return'<div class="playoff-team"><span class="pos top">'+(i+1)+'</span><strong>'+esc(r.team.name)+'</strong><span>'+r.stagePoints+' puntos en la etapa</span></div>';}).join('')+'</div><p class="desc">Cargá los puntajes desde Resultados. Los mejores puntajes avanzan automáticamente al confirmar la etapa.</p></div>':'';return'<section class="card"><div class="stage-hero"><div><p class="eyebrow">ETAPA ACTUAL</p><h2>'+LABELS[c.currentStage]+'</h2><p>Los equipos avanzan según puntos acumulados en la etapa.</p></div><div class="stage-count">'+(c.currentStage===STAGES.FINISHED?'✓':rows.length)+'<small>activos</small></div></div><div class="progress">'+[STAGES.GENERAL,STAGES.TOP_16,STAGES.TOP_8,STAGES.TOP_4,STAGES.SEMIFINAL,STAGES.FINAL].map(function(s,i){var index=[STAGES.GENERAL,STAGES.TOP_16,STAGES.TOP_8,STAGES.TOP_4,STAGES.SEMIFINAL,STAGES.FINAL].indexOf(c.currentStage);return'<div class="step '+(i<=index||c.currentStage===STAGES.FINISHED?'done ':'')+(s===c.currentStage?'current':'')+'"><span>'+(i<index||c.currentStage===STAGES.FINISHED?'✓':i+1)+'</span><small>'+LABELS[s]+'</small></div>';}).join('')+'</div>'+(c.currentStage===STAGES.FINISHED?'<div class="champions"><div><span>🥇</span><small>CAMPEÓN</small><strong>'+esc(winner?winner.name:'Pendiente')+'</strong></div><div><span>🥈</span><small>SUBCAMPEÓN</small><strong>'+esc(runner?runner.name:'Pendiente')+'</strong></div></div>':playoff+'<div class="stage-action"><div><b>¿Terminaste de cargar esta etapa?</b><span>Los eliminados conservan su historial.</span></div>'+action+'</div>')+'</section><div style="margin-top:17px">'+table()+'</div>';}
  function categoryPage(){var c=category();return categoryHeader(c)+(view==='teams'?teamsPage():view==='results'?resultsPage():view==='table'?table():stagePage());}
  function render(){try{var content=view==='categories'?categoriesPage():category()&&view!=='home'?categoryPage():home();app.innerHTML=shell(content);bind();}catch(error){console.error(error);app.innerHTML=shell('<section class="card empty"><h2>No se pudo cargar esta sección</h2><p>La interfaz sigue disponible. Volvé al inicio e intentá nuevamente.</p><button class="primary" data-view="home">Volver al inicio</button></section>');bind();}}
  function notice(message,ok){var n=document.getElementById('notice');if(n){n.className='notice '+(ok?'success':'error');n.textContent=message;}}
  function run(action,message){try{var value=action();render();notice(typeof message==='function'?message(value):message,true);}catch(error){notice(error.message||'No se pudo completar la operación.');}}
  function openModal(kind){modal.hidden=false;modal.innerHTML='<div class="modal-box"><h2>'+ (kind==='category'?'Nueva categoría':'Nuevo equipo')+'</h2><form class="form" data-form="modal-'+kind+'"><label>Nombre<input name="name" required autofocus placeholder="'+(kind==='category'?'Ej: Mixto +50':'Ej: Equipo A')+'"></label><div class="modal-actions"><button type="button" class="cancel" data-action="close">Cancelar</button><button class="primary">Guardar</button></div></form></div>';}
  function openDeleteCategoryModal(c,returnView){var count=teams(c.id).length,resultCount=results(c.id).length;modal.hidden=false;modal.innerHTML='<div class="modal-box danger-modal"><h2>¿Eliminar la categoría '+esc(c.name)+'?</h2><p class="modal-warning">Esta acción eliminará la categoría, sus equipos y todos los resultados asociados. Esta acción no se puede deshacer.</p><p class="modal-warning"><strong>Se eliminarán '+count+' '+(count===1?'equipo':'equipos')+' y todos sus resultados.</strong></p><p class="modal-detail">Resultados asociados: '+resultCount+'</p><div class="modal-actions"><button type="button" class="cancel" data-action="close">Cancelar</button><button type="button" class="primary modal-delete-confirm" data-action="confirm-delete-category" data-id="'+c.id+'" data-return-view="'+returnView+'">Eliminar categoría</button></div></div>';}
  function closeModal(){modal.hidden=true;modal.innerHTML='';}
  function bind(){
    app.querySelectorAll('[data-view]').forEach(function(e){e.onclick=function(){view=e.getAttribute('data-view');render();};});
    app.querySelectorAll('[data-category]').forEach(function(e){e.onclick=function(){selectCategory(e.getAttribute('data-category'),'teams');};});
    app.querySelectorAll('[data-action="select-category"]').forEach(function(e){e.onchange=function(){selectCategory(e.value,'results');};});
    app.querySelectorAll('[data-action="theme"]').forEach(function(e){e.onclick=function(){theme=theme==='dark'?'light':'dark';state.theme=theme;document.documentElement.setAttribute('data-theme',theme);saveState();render();};});
    app.querySelectorAll('[data-action="new-category"]').forEach(function(e){e.onclick=function(){openModal('category');};});
    app.querySelectorAll('[data-action="new-team"]').forEach(function(e){e.onclick=function(){openModal('team');};});
    app.querySelectorAll('[data-action="advance"]').forEach(function(e){e.onclick=function(){run(function(){var c=category();if(c.currentStage===STAGES.GENERAL)generateTop16();else if(c.currentStage===STAGES.TOP_16)generateTop8();else if(c.currentStage===STAGES.TOP_8)generateTop4();else if(c.currentStage===STAGES.TOP_4)advanceToSemifinals();else advanceToFinal();},'Etapa avanzada.');};});
    app.querySelectorAll('[data-action="finish"]').forEach(function(e){e.onclick=function(){run(finishTournament,'Campeón y subcampeón determinados.');};});
    app.querySelectorAll('[data-action="edit-category"]').forEach(function(e){e.onclick=function(){var c=state.categories.filter(function(x){return x.id===e.getAttribute('data-id');})[0],name=prompt('Nuevo nombre de categoría:',c?c.name:'');if(c&&name!==null)run(function(){editCategory(c.id,name);},'Categoría actualizada.');};});
    app.querySelectorAll('[data-action="delete-category"],[data-action="delete-active-category"]').forEach(function(e){e.onclick=function(){var c=state.categories.filter(function(x){return x.id===e.getAttribute('data-id');})[0];if(c)openDeleteCategoryModal(c,e.getAttribute('data-action')==='delete-active-category'?'category':'categories');};});
    app.querySelectorAll('[data-action="delete-result"]').forEach(function(e){e.onclick=function(){if(confirm('¿Eliminar este puntaje?')){deleteResult(e.getAttribute('data-id'));render();notice('Puntaje eliminado y tabla recalculada.',true);}};});
    app.querySelectorAll('[data-form="team"]').forEach(function(f){f.onsubmit=function(ev){ev.preventDefault();run(function(){createTeam(new FormData(f).get('name'));},'Equipo guardado.');};});
    app.querySelectorAll('[data-form="result"]').forEach(function(f){f.onsubmit=function(ev){ev.preventDefault();run(function(){var d=new FormData(f);addResult(d.get('teamId'),d.get('points'));},'Puntaje guardado y tabla actualizada.');};});
    app.querySelectorAll('[data-form="quick-results"]').forEach(function(f){f.onsubmit=function(ev){ev.preventDefault();run(function(){var entries=Array.from(f.querySelectorAll('[data-team-id]')).map(function(input){return{teamId:input.getAttribute('data-team-id'),value:input.value};});return addQuickResults(entries);},function(count){return count+' puntaje'+(count===1?'':'s')+' guardado'+(count===1?'':'s')+'.'});};});
  }
  modal.onclick=function(e){if(e.target===modal||e.target.closest('[data-action="close"]')){closeModal();return;}var confirmButton=e.target.closest('[data-action="confirm-delete-category"]');if(confirmButton){try{var returnView=confirmButton.getAttribute('data-return-view'),c=state.categories.filter(function(x){return x.id===confirmButton.getAttribute('data-id');})[0],name=c?c.name:'Categoría';deleteCategory(confirmButton.getAttribute('data-id'));closeModal();view=state.categories.length?(returnView==='category'?'teams':'categories'):'home';render();notice(name+' eliminada correctamente.',true);}catch(error){console.error(error);}}};
  modal.onsubmit=function(e){e.preventDefault();var f=e.target;try{var name=new FormData(f).get('name');if(f.getAttribute('data-form')==='modal-category'){createCategory(name);view='teams';}else createTeam(name);closeModal();render();notice('Guardado correctamente.',true);}catch(error){var input=f.querySelector('input');input.setCustomValidity(error.message);input.reportValidity();input.setCustomValidity('');}};
  state=loadState();theme=state.theme==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',theme);
  window.PuntajeNewcom={getState:function(){return JSON.parse(JSON.stringify(state));},createCategory:createCategory,deleteCategory:deleteCategory,createTeam:createTeam,addResult:addResult,addQuickResults:addQuickResults,generateTop16:generateTop16,generateTop8:generateTop8,generateTop4:generateTop4,advanceToSemifinals:advanceToSemifinals,advanceToFinal:advanceToFinal,finishTournament:finishTournament,calculateStandings:standings,calculateTeamPoints:function(id){return state.results.filter(function(r){return r.teamId===id;}).reduce(function(total,r){return total+r.points;},0);},loadState:loadState,saveState:saveState};
  render();
}());
